### ISSUE TITLE
Parse YAML

### ISSUE THREAD

**Issue by longfangsong** [SHUReeducation/autoAPI#3]
Get Table name and fields info from yaml files

**Comment by longfangsong** [comment]
yaml examples:

```yaml
dbengin: pgsql
tablename: test
fields:
  - name: id
    type: bigserial
  - name: name
    type: varchar
```
