### ISSUE TITLE
Generate k8s deployment yaml

### ISSUE THREAD

**Issue by longfangsong** [SHUReeducation/autoAPI#9]
eg.
```yaml
k8s:
  db: "postgres://xxx@shu-student-postgres-svc:5432/shu-student?sslmode=disable"
```

Should generate:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shu-student
spec:
  selector:
    matchLabels:
      run: shu-student
  replicas: 1
  template:
    metadata:
      labels:
        run: shu-student
    spec:
      containers:
      - name: shu-student
        image: xxx/shu-student:138153507
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DB_ADDRESS
          value: "postgres://xxx@shu-student-postgres-svc:5432/shu-student?sslmode=disable"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: shu-student-svc
spec:
  selector:
     run: shu-student
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
```

And if no `k8s` entry exists, nothing should be generated.
